# NumPy

* Manejo de arranjos de dados

* Se o volume de dados é muito grande com um grande número de operações, o uso de lista pode exigir muito tempo de processamento porque a interpretação de listas em Python não foi feita para otimizar o tempo de processamento.
* Os elementos de uma lista são distribuidos de uma maneira não contínua na memória do computador e seus elementos podem possuir tamanhos diferentes, o que aumenta o tempo de processamento.

* O NumPy introduz um novo tipo de dados: **ndarray** (*n-dimensional array*).

* Foi desenvolvido para ser processado de maneira otimizada (50 vezes mais rápido do que listas).

In [ ]:
lista = [1, 2, 3, 4, 5] 
tupla = (10, 20, 30)

## Instalando e importando o NumPy

In [ ]:
# Instalação do PACOTE numpy (o sistema operacional instala o pacote, o Python importa módulos)
! pip install numpy

In [ ]:
# Importando o MÓDULO numpy
import numpy as np

## Criando arrays com o NumPy

In [ ]:
# Criando um arranjo 1D:
import numpy as np

arr1D = np.array( [1, 2, 3, 4, 5] )
print( arr1D, type(arr1D) )         # Converteu lista -> ndarray

[1 2 3 4 5] <class 'numpy.ndarray'>


In [ ]:
# Criando um arranjo 1D:
import numpy as np

arr1Db = np.array( (10, 20, 30) )
print( arr1Db, type(arr1Db) )      # Converteu tupla -> ndarray

[10 20 30] <class 'numpy.ndarray'>


In [ ]:
# Criando um arranjo 2D:
import numpy as np

arr2D = np.array( [ [1,2,3], [4,5,6] ] )

print( arr2D )

[[1 2 3]
 [4 5 6]]


In [ ]:
# Criando um arranjo 3D:
import numpy as np

arr3D = np.array( [ [ (1,2,3), (4,5,6) ], [ (7,8,9), (10,11,12) ] ] )

print( arr3D )

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [ ]:
# Criando um arranjo 0D:
import numpy as np

arr0D = np.array( 3.1416 )

print( arr0D, type(arr0D) )

3.1416 <class 'numpy.ndarray'>


## Checando o número de dimensões e a forma de um array

* Sintaxe:

```
array.ndim
array.shape
```

In [ ]:
print( arr0D.ndim )
print( arr1D.ndim )
print( arr2D.ndim )
print( arr3D.ndim )

print()
print( len(arr1D) )
print( len(arr2D) )
print( len(arr3D) )
print( len(arr0D) )  # Como tem dimensão 0, len retorna exceção (assim como um inteiro, p.e.)

0
1
2
3

5
2
2


TypeError: ignored

In [ ]:
print( arr0D.shape, type(arr0D.shape) )  # .shape cria uma tupla com o número de elemento de cada dimensão¹
print( arr1D.shape )  # 5 linhas
print( arr2D.shape )  # 2 linhas e 3 colunas
print( arr3D.shape )  # 2 matrizes, 2 linhas e 3 colunas

# ¹arr1D.shape tem uma vírgula pq a tupla precisa quando tem apenas um elemento

() <class 'tuple'>
(5,)
(2, 3)
(2, 2, 3)


## Criando um arranjo com n-dimensões

* Analogia das dimensões D com livros:

D

1 - índice da palavra na linha da página do livro

2 - índice da linha da página do livro

3 - índice da página do livro

4 - índice do livro na prateleira

5 - índice da prateleira da estante

6 - índice da estante no corredor

7 - índice do corredor na biblioteca

8 - índice da biblioteca na cidade

In [ ]:
# Criando um arranjo 5D:
import numpy as np

arr5D = np.array( [1, 2, 3, 4, 5], ndmin=5 )  # Número mínimo de dimensões

print( arr5D )
print( arr5D.ndim )
print( arr5D.shape )

# (1, 1, 1, 1, 5)
# 1 : 1ª índice da prateleira na estante
# 1 : 2ª índice do livro da prateleira
# 1 : 3ª índice da página no livro
# 1 : 4ª índice da linha na matriz (na página do livro)
# 5 : 5ª índice da coluna na linha da matriz

[[[[[1 2 3 4 5]]]]]
5
(1, 1, 1, 1, 5)


## Acessando elementos de um arranjo

* Diferentemente de listas, por exemplo, é possível acessar arranjos fazendo:

```
arranjo[...,índice3,índice2,índice1]
```

* Mas também pode acessar usando a sintaxe de listas:

```
arranjo[...][índice3][índice2][índice1]
```

In [ ]:
# 1D:
import numpy as np

arr1D = np.array( [1, 2, 3, 4, 5] )

print( arr1D[1] )
print( arr1D[0] + arr1D[4] )

2
6


In [ ]:
# 2D:
import numpy as np

arr2D = np.array( [ [1,2,3], [4,5,6] ] )

print( arr2D )

print()
print( "arr2D[0,1] =", arr2D[0,1] )
print( "arr2D[1,2] =", arr2D[1,2] )

print()
print( arr2D[0][1] )
print( arr2D[1][2] )

# lista = [ [1,2,3], [4,5,6] ]
# print( lista[1,2] )           # Lista não funciona como arranjos

[[1 2 3]
 [4 5 6]]

arr2D[0,1] = 2
arr2D[1,2] = 6

2
6


In [ ]:
# 3D:
import numpy as np

arr3D = np.array( [ [ (1,2,3), (4,5,6) ], [ (7,8,9), (10,11,12) ] ] )

print( arr3D )
print()

print( "arr3D[0,1,1] =", arr3D[0,1,1] )
print( "arr3D[1,1,2] =", arr3D[1,1,2] )

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

arr3D[0,1,1] = 5
arr3D[1,1,2] = 12


## Índices negativos

In [ ]:
# 2D:
import numpy as np

arr2D = np.array( [ [1,2,3], [4,5,6] ] )

print( arr2D )

print()
print( "arr2D[1,2] =", arr2D[1, 2])
print( "arr2D[-1,-1] =", arr2D[1, -1])
print( "arr2D[-1,-1] =", arr2D[-1, -1])

print()
print( "arr2D[1,1] =", arr2D[1, 1])
print( "arr2D[1,-2] =", arr2D[1, -2])
print( "arr2D[-1,-2] =", arr2D[-1, -2])

[[1 2 3]
 [4 5 6]]

arr2D[1,2] = 6
arr2D[-1,-1] = 6
arr2D[-1,-1] = 6

arr2D[1,1] = 5
arr2D[1,-2] = 5
arr2D[-1,-2] = 5


## Fatiamento

* O fatiamento pode conter três informações para cada dimensão:

```
             1ª dimensão               2ª dimensão
array[início1 : fim1+1 : step1, início2 : fim2+1 : step2, ...]
```

In [ ]:
# 1D:
import numpy as np

arr1D = np.array( [1, 2, 3, 4, 5, 6, 7] )

print( arr1D )

print()
print( arr1D[1:5] )
print( arr1D[0:5] )
print( arr1D[5:] )

print()
print( arr1D[-3:-1] )  # Índices negativos

print()
print( arr1D[1:5:2] )  # Step
print( arr1D[ : :2] )  # Step

[1 2 3 4 5 6 7]

[2 3 4 5]
[1 2 3 4 5]
[6 7]

[5 6]

[2 4]
[1 3 5 7]


In [ ]:
# 2D:
import numpy as np

arr2D = np.array( [ [1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15] ] )
                    #0           1             2
                    #0 1 2 3 4    0 1 2 3  4     0  1  2  3  4
print( arr2D )

print()
print( arr2D[1, 1:4] )    # Linha 1 da matriz e colunas da 1 até a 4
print( arr2D[0:2, 2] )    # Linhas 0 e 1 da matriz e coluna 2 (de cada)

print()
print( arr2D[0:2, 1:4] )  # Linhas 0 e 1 da matriz e colunas de 1 até 4

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

[7 8 9]
[3 8]

[[2 3 4]
 [7 8 9]]


## Métodos .copy() e .view()

* **.copy()** cria um novo *array* com valores iguais (alteração em um **não causa** alteração no outro).

* **.view()** cria outra atribuição para o mesmo *array* (alteração em um **causa** alteração no outro).

* **.base** atributo que indica se o arranjo é proprietário dos dados ou não.

In [ ]:
# Método .copy():
import numpy as np

arr1D = np.array( [1, 2, 3, 4, 5, 6, 7] )

x = arr1D.copy()

arr1D[0] = -111

print( arr1D )
print( x )

print()
print( arr1D.base )  # None : arranjo é proprietário dos dados
print( x.base )

[-111    2    3    4    5    6    7]
[1 2 3 4 5 6 7]

None
None


In [ ]:
# Método .view():
import numpy as np

arr1D = np.array( [1, 2, 3, 4, 5, 6, 7] )

x = arr1D.view()

arr1D[0] = -111

print( arr1D )
print( x )

print()
print( arr1D.base )  # None : arranjo é proprietário dos dados
print( x.base )      # Não é proprietário dos dados

[-111    2    3    4    5    6    7]
[-111    2    3    4    5    6    7]

None
[-111    2    3    4    5    6    7]


In [ ]:
# Método .view():
import numpy as np

arr1D = np.array( [1, 2, 3, 4, 5, 6, 7] )

x = arr1D.view()

x[0] = -111

print( arr1D )
print( x )

[-111    2    3    4    5    6    7]
[-111    2    3    4    5    6    7]


## Método reshape()

* Altera a forma de um *array*

In [ ]:
# Transformar: 1D --> 2D
import numpy as np

arr1D = np.array( [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] )
print( arr1D, '\n', arr1D.shape )

print()
newarr = arr1D.reshape(3,4)
print( newarr, '\n', newarr.shape )

[ 1  2  3  4  5  6  7  8  9 10 11 12] 
 (12,)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]] 
 (3, 4)


In [ ]:
# Transformar: 1D --> 2D
import numpy as np

arr1D = np.array( [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] )
print( arr1D, '\n', arr1D.shape )

print()
newarr = arr1D.reshape(2,3,2)
print( newarr, '\n', newarr.shape )

[ 1  2  3  4  5  6  7  8  9 10 11 12] 
 (12,)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] 
 (2, 3, 2)


In [ ]:
# O que acontece se o número de elementos não for suficiente?
# Transformar: 1D --> 2D
import numpy as np

arr1D = np.array( [1, 2, 3, 4, 5, 6, 7, 8] )
print( arr1D, '\n', arr1D.shape )

print()
newarr = arr1D.reshape(2,3,2)        # Erro!
print( newarr, '\n', newarr.shape )

[1 2 3 4 5 6 7 8] 
 (8,)



ValueError: ignored

In [ ]:
# O novo arranjo é copy ou view?
# Transformar: 1D --> 2D
import numpy as np

arr1D = np.array( [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] )
print( arr1D, '\n', arr1D.shape )

print()
newarr = arr1D.reshape(2,3,2)
print( newarr, '\n', newarr.shape )
print( newarr.base )  # Não é uma proprietário (não é uma cópia independente!)

[ 1  2  3  4  5  6  7  8  9 10 11 12] 
 (12,)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] 
 (2, 3, 2)
[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
# Como não são independentes, alterar arr1D altera newarr:
arr1D[1] = -222
print( arr1D )
print()
print( newarr )

[   1 -222    3    4    5    6    7    8    9   10   11   12]

[[[   1 -222]
  [   3    4]
  [   5    6]]

 [[   7    8]
  [   9   10]
  [  11   12]]]


In [ ]:
# Como não são independentes, alterar newarr altera arr1D:
newarr[1,1,0] = -777
print( arr1D )
print()
print( newarr )

[   1 -222    3    4    5    6    7    8 -777   10   11   12]

[[[   1 -222]
  [   3    4]
  [   5    6]]

 [[   7    8]
  [-777   10]
  [  11   12]]]


In [ ]:
# Para 'cópias independentes' ao usar reshape, utilize .copy:
# Transformar: 1D --> 2D
import numpy as np

arr1D = np.array( [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12] )
print( arr1D, '\n', arr1D.shape )

print()
newarr = arr1D.reshape(2,3,2).copy()
print( newarr, '\n', newarr.shape )
print( newarr.base )  # Utilizando .copy ele vira proprietário

[ 1  2  3  4  5  6  7  8  9 10 11 12] 
 (12,)

[[[ 1  2]
  [ 3  4]
  [ 5  6]]

 [[ 7  8]
  [ 9 10]
  [11 12]]] 
 (2, 3, 2)
None


In [ ]:
# Dimensão desconhecida:
# Transformar: 1D --> 2D
import numpy as np

arr1D = np.array( [1, 2, 3, 4, 5, 6, 7, 8] )
print( arr1D, '\n', arr1D.shape )

print()
newarr = arr1D.reshape(2, 2, -1)  # O -1 indica que a dimensão é desconhecida
print( newarr, '\n', newarr.shape )

# Determinamos que seriam duas matrizes com duas linhas cada, mas as colunas
# deixamos em aberto para o Python calcular indicando com '-1'
# Note que só é possível indicar uma dimensão desconhecida.

[1 2 3 4 5 6 7 8] 
 (8,)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]] 
 (2, 2, 2)


In [ ]:
# Achatamento de um array: nD --> 1D
import numpy as np

arrnd = np.array( [ [1,2,3], [4,5,6] ] )
print( arrnd )

newarr = arrnd.reshape(-1)  # Queremos apenas 1 dimensão e o Python vai calcular
                            # quantos elementos terá

print( newarr )

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


## Iterando os elementos de um arranjo

In [ ]:
# 1D:
import numpy as np

arr1D = np.array( [1, 2, 3, 4, 5] )
print( arr1D )
print()

for x in arr1D:
  print(x)

[1 2 3 4 5]
1
2
3
4
5


In [ ]:
# 2D
import numpy as np

arr2D = np.array( [ [1,2,3], [4,5,6] ] )
print( arr2D )
print()

for linha in arr2D:
  for x in linha:
    print(x)

[[1 2 3]
 [4 5 6]]

1
2
3
4
5
6


In [ ]:
# 3D:
import numpy as np

arr3D = np.array( [ [ (1,2,3), (4,5,6) ], [ (7,8,9), (10,11,12) ] ] )
print( arr3D )
print()

for matriz in arr3D:
  for linha in matriz:
    for x in linha:
      print(x)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

1
2
3
4
5
6
7
8
9
10
11
12


### Iterando com a função nditer()

In [ ]:
# 3D:
import numpy as np

arr3D = np.array( [ [ (1,2,3), (4,5,6) ], [ (7,8,9), (10,11,12) ] ] )
print( arr3D )
print()

for x in np.nditer(arr3D):
  print(x)
print()

for x in np.nditer(arr3D[:,1,:2:2]):
  print(x)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

1
2
3
4
5
6
7
8
9
10
11
12

4
10


### Iterando com a função ndenumerate()
 * **np.ndenumerate(arranjo)** retorna uma tupla com dois elementos: o primeiro é o índice e o segundo é o valor do elemento do arranjo.

In [ ]:
# 3D:
import numpy as np

arr3D = np.array( [ [ (1,2,3), (4,5,6) ], [ (7,8,9), (10,11,12) ] ] )
print( arr3D )
print()

for x in np.ndenumerate(arr3D):
  print(x)
print()

# O primeiro elemento são os índices e o segundo, o valor
for i, x in np.ndenumerate(arr3D):
  print(x)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]

((0, 0, 0), 1)
((0, 0, 1), 2)
((0, 0, 2), 3)
((0, 1, 0), 4)
((0, 1, 1), 5)
((0, 1, 2), 6)
((1, 0, 0), 7)
((1, 0, 1), 8)
((1, 0, 2), 9)
((1, 1, 0), 10)
((1, 1, 1), 11)
((1, 1, 2), 12)

1
2
3
4
5
6
7
8
9
10
11
12


## Juntando arranjos

* **np.concatenate(tupla com arranjos)**: coloca os arranjos na mesma linha.

* **np.stack(tupla com arranjos, aixs=número)**: coloca os arranjos empilhados de acordo com o eixo definido.

* **np.hstack(tupla com arranjos)**: equivalente ao **np.concatenate()**

* **np.vstack(tupla com arranjos)**: equivalente ao **np.stack(, axis=0)**

In [ ]:
# Por concatenação: np.concatenate()
import numpy as np

arr1 = np.array( [1,2,3] )
arr2 = np.array( [4,5,6] )

arr = np.concatenate( (arr1,arr2) )

print(arr)

[1 2 3 4 5 6]


In [ ]:
# Por empilhamento: np.stack(, axis=0)
import numpy as np

arr1 = np.array( [1,2,3] )
arr2 = np.array( [4,5,6] )

arr = np.stack( (arr1,arr2), axis=0 )

print(arr)

[[1 2 3]
 [4 5 6]]


In [ ]:
# Por empilhamento: np.stack(, axis=1)
import numpy as np

arr1 = np.array( [1,2,3] )
arr2 = np.array( [4,5,6] )

arr = np.stack( (arr1,arr2), axis=1 )

print(arr)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
# np.hstack() = np.concatenate()
import numpy as np

arr1 = np.array( [1,2,3] )
arr2 = np.array( [4,5,6] )

arr = np.hstack( (arr1,arr2) )

print(arr)

[1 2 3 4 5 6]


In [ ]:
# np.vstack() = np.stack(, axis=0)
import numpy as np

arr1 = np.array( [1,2,3] )
arr2 = np.array( [4,5,6] )

arr = np.vstack( (arr1,arr2) )

print(arr)

[[1 2 3]
 [4 5 6]]


## Separando arranjos

* **np.array_split( arranjo, número de partes, axis= )**: divide o arranjo em uma lista de arranjos; o eixo pode ser definido, sendo o *default* 0.

* **np.hsplit(arranjo, número de partes)**: equivale a **np.array_split(, axis=1)**

* **np.vsplit(arranjo, número de partes)**: equivale a **np.array_split(, axis=0)**

In [ ]:
# Função np.array_split()
import numpy as np

arr = np.array( [1,2,3,4,5,6] )

newarr = np.array_split( arr, 3 )

print( newarr )
print()

print( newarr[0] )
print( newarr[1] )
print( newarr[2] )

[array([1, 2]), array([3, 4]), array([5, 6])]

[1 2]
[3 4]
[5 6]


In [ ]:
# Função np.array_split()
import numpy as np

arr = np.array( [1,2,3,4,5,6] )

newarr = np.array_split( arr, 4 )

print( newarr )
print()

print( newarr[0] )
print( newarr[1] )
print( newarr[2] )
print( newarr[3] )

[array([1, 2]), array([3, 4]), array([5]), array([6])]

[1 2]
[3 4]
[5]
[6]


In [ ]:
# 2D:
import numpy as np

arr = np.array( [ [1,2], [3,4], [5,6], [7,8], [9,10], [11,12] ] )
print( arr )
print()

newarr = np.array_split(arr, 3)
print( newarr )
print()

print( newarr[0] )
print( newarr[1] )
print( newarr[2] )

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]

[array([[1, 2],
       [3, 4]]), array([[5, 6],
       [7, 8]]), array([[ 9, 10],
       [11, 12]])]

[[1 2]
 [3 4]]
[[5 6]
 [7 8]]
[[ 9 10]
 [11 12]]


In [ ]:
import numpy as np

arr = np.array( [ [1,2,3], [4,5,6], [7,8,9], [10,11,12], [13,14,15], [16,17,18] ] )
print(arr)
print()

newarr = np.array_split(arr, 3)
print()

print( newarr[0] )
print( newarr[1] )
print( newarr[2] )

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[13 14 15]
 [16 17 18]]


In [ ]:
import numpy as np

arr = np.array( [ [1,2,3], [4,5,6], [7,8,9], [10,11,12], [13,14,15], [16,17,18] ] )
print(arr)
print()

newarr = np.array_split(arr, 3, axis=1)
print()

print( newarr[0] )
print( newarr[1] )
print( newarr[2] )

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


[[ 1]
 [ 4]
 [ 7]
 [10]
 [13]
 [16]]
[[ 2]
 [ 5]
 [ 8]
 [11]
 [14]
 [17]]
[[ 3]
 [ 6]
 [ 9]
 [12]
 [15]
 [18]]


In [ ]:
import numpy as np

arr = np.array( [ [1,2,3], [4,5,6], [7,8,9], [10,11,12], [13,14,15], [16,17,18] ] )
print(arr)
print()

newarr = np.array_split(arr, 3, axis=0)  # Default = 0
print()

print( newarr[0] )
print( newarr[1] )
print( newarr[2] )

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[13 14 15]
 [16 17 18]]


In [ ]:
import numpy as np

arr = np.array( [ [1,2,3], [4,5,6], [7,8,9], [10,11,12], [13,14,15], [16,17,18] ] )
print(arr)
print()

newarr = np.hsplit(arr, 3)  # Equivalente a np.array_split(, axis=1)
print()

print( newarr[0] )
print( newarr[1] )
print( newarr[2] )

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


[[ 1]
 [ 4]
 [ 7]
 [10]
 [13]
 [16]]
[[ 2]
 [ 5]
 [ 8]
 [11]
 [14]
 [17]]
[[ 3]
 [ 6]
 [ 9]
 [12]
 [15]
 [18]]


In [ ]:
import numpy as np

arr = np.array( [ [1,2,3], [4,5,6], [7,8,9], [10,11,12], [13,14,15], [16,17,18] ] )
print(arr)
print()

newarr = np.vsplit(arr, 3)  # Equivalente a np.array_split(, axis=0)
print()

print( newarr[0] )
print( newarr[1] )
print( newarr[2] )

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]


[[1 2 3]
 [4 5 6]]
[[ 7  8  9]
 [10 11 12]]
[[13 14 15]
 [16 17 18]]


## Pesquisa por elementos em um arranjo

* **np.where(condição)**: retorna uma tupla contendo arranjos com os índices dos elementos que satisfazem a condição.

* **np.searchsorted(arranjo, número)**: retorna o índice onde o número deveria ser colocado para que ficasse em ordem ascendente.

In [ ]:
# np.where()
import numpy as np

arr = np.array( [10,20,30,40,10,20,30,40,10,20,30,40] )

x = np.where( arr == 40 )

print(x)  # Retorna os índices dos elementos que satisfazem a condição dada

(array([ 3,  7, 11]),)


In [ ]:
# np.where()
import numpy as np

arr = np.array( [1,2,3,4,5,6,7,8,9,10] )

pares = np.where( arr % 2 == 0 )
impares = np.where( arr % 2 == 1 )

print(pares)
print(impares)

print(type(pares), type(pares[0]))

(array([1, 3, 5, 7, 9]),)
(array([0, 2, 4, 6, 8]),)
<class 'tuple'> <class 'numpy.ndarray'>


In [ ]:
# 2D: quando o arranjo tem mais de uma dimensão, cada elemento da tupla recebe
# um arranjo com a posição de uma dimensão de modo que os índices do elemento
# que satisfez a condição é dado pelo conjunto de elementos de mesmo índice dos
# de cada arranjo
import numpy as np

arr2D = np.array( [ [1,2,3], [4,5,6], [7,8,9], [10,11,12], [13,14,15], [16,17,18] ] )
print(arr2D)
print()

pares = np.where( arr2D % 2 == 0 )
impares = np.where( arr2D % 2 == 1 )

print(pares)
print(impares)

# Por exemplo o índice do número par 2 é obtido pegando o primeiro número de
# cada arranjo (0 e 1)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]
 [16 17 18]]

(array([0, 1, 1, 2, 3, 3, 4, 5, 5]), array([1, 0, 2, 1, 0, 2, 1, 0, 2]))
(array([0, 0, 1, 2, 2, 3, 4, 4, 5]), array([0, 2, 1, 0, 2, 1, 0, 2, 1]))


In [ ]:
# np.searchsorted():
# arr[i-1] < v <= arr[i] (left) (default)
# arr[i-1] <= v < arr[i] (right)
import numpy as np

arr = np.array( [6, 7, 8, 9] )

x = np.searchsorted(arr, 8)
print(x)

print()
y = np.searchsorted(arr, 8, side='right')
print(y)

2

3


## Ordenamento de arranjos

* **np.sort(arranjo)**: ordena os elementos em ordem ascendente (serve para números e *strings*).

In [ ]:
# np.sort():
import numpy as np

arr = np.array( [3,2,0,1] )

print( np.sort(arr) )

[0 1 2 3]


In [ ]:
# np.sort():
import numpy as np

arr = np.array( ['Be', 'C', 'H', 'He', 'O'] )

print( np.sort(arr) )

['Be' 'C' 'H' 'He' 'O']


In [ ]:
# np.sort():
import numpy as np

arr = np.array( [True, True, False, False, True, False] )

print( np.sort(arr) )  # False é 0 e True é qualquer coisa que não 0

[False False False  True  True  True]


In [ ]:
# np.sort():
import numpy as np

arr = np.array( [ [3,2,4], [5,0,1] ] )

print( np.sort(arr) )

[[2 3 4]
 [0 1 5]]


In [ ]:
# EXEMPLO:
import numpy as np

arr = np.array( [ [3,2,4], [5,0,1] ])
print(arr)
print() 

new = np.sort( arr.reshape(6) ).reshape(2,3)
print( arr.reshape(6) )
print()
print(new)

[[3 2 4]
 [5 0 1]]

[3 2 4 5 0 1]

[[0 1 2]
 [3 4 5]]


## Filtrando arranjos

* 

In [ ]:
# Exemplo 1: Filtragem de arranjo
import numpy as np

arr = np.array( [10,20,30,40,50,60,70,80] )
print(arr)

x = [True, True, False, False, False, True, True, True]

newarr = arr[x]
print(newarr)

[10 20 30 40 50 60 70 80]
[10 20 60 70 80]


In [ ]:
# Exemplo 2: Criando um filtro que retorna um arranjo com valores maiores que 40
import numpy as np

arr = np.array( [10,20,30,40,50,60,70,80] )
print(arr)

filtro = []

for elemento in arr:
  print(elemento)
  if elemento > 40:
    filtro.append(True)
  else:
    filtro.append(False)
print(filtro)

newarr = arr[filtro]

print(newarr)

[10 20 30 40 50 60 70 80]
10
20
30
40
50
60
70
80
[False, False, False, False, True, True, True, True]
[50 60 70 80]


In [ ]:
# Exemplo 3: Criando um filtro que retorna os elementos pares de um arranjo
import numpy as np

arr = np.array( range(1,20) )
print(arr)

filtro = []

for elemento in arr:
  if elemento % 2 == 0:
    filtro.append(True)
  else:
    filtro.append(False)
print(filtro)

newarr = arr[filtro]
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False, True, False]
[ 2  4  6  8 10 12 14 16 18]


In [ ]:
# Exemplo 4: Criando um filtro diretamente para o exemplo 2
import numpy as np

arr = np.array( [10,20,30,40,50,60,70,80] )
print(arr)

filtro = arr > 40  # Esse operador foi redefinido para funcionar iterativamente
print(filtro)

newarr = arr[filtro]

print(newarr)

[10 20 30 40 50 60 70 80]
[False False False False  True  True  True  True]
[50 60 70 80]


In [ ]:
# Exemplo 5: Criando um filtro diretamente para o exemplo 3
import numpy as np

arr = np.array( range(1,20) )
print(arr)

filtro = arr % 2 == 0
print(filtro)

newarr = arr[filtro]
print(newarr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]
[False  True False  True False  True False  True False  True False  True
 False  True False  True False  True False]
[ 2  4  6  8 10 12 14 16 18]


In [ ]:
# Exemplo 6: Criando um filtro diretamente para extrair elementos ímpares
import numpy as np

arr = np.array( range(1,20) )
print( arr[ arr % 2 == 1 ] )

[ 1  3  5  7  9 11 13 15 17 19]


## Números Pseudo-Randômicos

* Um gerador de números aleatórios (ou randômicos) é um processo que não pode ser previsto a partir de todos os números gerados anteriormente.

* Para gerar valores numéricos em computador é nessário um algorímo, por tanto existe uma lógica por trás do processo do número que ele gera e conhecendo essa lógica é possível prever o próximo valor gerado.

* Por isso se utiliza o termo **pseudo-randômicos**.

* Seria possível utilizar um gerador de números realmente aleatório, mas para isso seria necessário um valor que viesse de fora do algoritmo, do ambiente, como semente para o próximo número aleatório. Um exemplo é a posição do *mouse* em algum instante.

* Na prática, principalmente se você não conhece a lógica por trás do código, um gerador pseudo-randômico terá o mesmo efeito que um gerador randômico.

* O uso de gerador verdadeiramente randômico faz diferença em algumas situações específicas, por exemplo em criptografia, por questões de segurança.


In [ ]:
# Gerando números pseudo-randômicos inteiros:
# Vamos importar o módulo random da biblioteca numpy
from numpy import random

x = random.randint(100)
print(x)

20


In [ ]:
# Gerando números pseudo-randômicos reais (float):
print( random.rand() )  # Sem argumentos gera números entre 0 e 1

0.7380649172142365


In [ ]:
# Gerando arranjos de números inteiros pseudo-randômicos:
print( random.randint(100, size=10) )

[16 30  4 94 61 74  5  0 21 71]


In [ ]:
# Gerando arranjos 2D de números inteiros pseudo-randômicos:
print( random.randint(100, size=(3,5)) )

[[97 64 46 87 84]
 [48 28 57  6 58]
 [68 63 62 65 70]]


In [ ]:
# Gerando arranjos de números reais pseudo-randômicos (floats):
print( random.rand(10) )

[0.92957923 0.97101716 0.60205828 0.99146446 0.27565108 0.00993385
 0.30469385 0.61207059 0.83446382 0.15017509]


In [ ]:
# Gerando arranjo 2D de números reais pseudo-randômicos (floats):
print( random.rand(3,5) )

[[0.47532679 0.73250511 0.14261697 0.45997913 0.86518101]
 [0.51871354 0.98299182 0.06631519 0.38248313 0.54971663]
 [0.28304682 0.72392701 0.99450933 0.07965415 0.03054382]]


In [ ]:
help( random.rand )

Help on built-in function rand:

rand(...) method of numpy.random.mtrand.RandomState instance
    rand(d0, d1, ..., dn)
    
    Random values in a given shape.
    
    .. note::
        This is a convenience function for users porting code from Matlab,
        and wraps `random_sample`. That function takes a
        tuple to specify the size of the output, which is consistent with
        other NumPy functions like `numpy.zeros` and `numpy.ones`.
    
    Create an array of the given shape and populate it with
    random samples from a uniform distribution
    over ``[0, 1)``.
    
    Parameters
    ----------
    d0, d1, ..., dn : int, optional
        The dimensions of the returned array, must be non-negative.
        If no argument is given a single Python float is returned.
    
    Returns
    -------
    out : ndarray, shape ``(d0, d1, ..., dn)``
        Random values.
    
    See Also
    --------
    random
    
    Examples
    --------
    >>> np.random.rand(3,2)
    arra

In [ ]:
# Gerando valor aleatório entre 10 e 20:
x = 10 + random.rand(10) * 10
print(x)

[15.81468331 11.72742291 12.75665992 10.62131567 13.03959189 15.1966734
 16.81072536 17.94369903 18.17282886 12.18585428]


### Função random.choice()

* Retorna um valor de uma coleção de dados ordenada escolhida aleatoriamente.

In [ ]:
# Escolhendo um número aleatorimanete de uma lista 1D:
x = random.choice( [1,3,5,7,9] )
print(x)

7


In [ ]:
# Escolhendo números aleatorimanete de uma lista 1D retornando uma lista:
x = random.choice( [1,3,5,7,9], size=10 )
print(x)

[1 5 1 1 1 3 5 5 1 5]


In [ ]:
# Escolhendo números aleatorimanete de uma lista 1D retornando uma matriz:
x = random.choice( [1,3,5,7,9], size=(3,5) )
print(x)

[[1 1 5 9 9]
 [3 9 9 7 5]
 [3 3 9 1 3]]


In [ ]:
# Escolhendo um número aleatorimanete de uma tupla 1D:
x = random.choice( (1,3,5,7,9) )
print(x)

5


In [ ]:
# Erro: não funciona com coleções de dados não ordenados
x = random.choice( {1,3,5,7,9} )
print(x)

ValueError: ignored

In [ ]:
# Erro: a coleção de dados tem que ser unidimensional
x = random.choice( [ [1,3], [5,7], [9,10] ] )
print(x)

ValueError: ignored

### Sementes de números pseudo-randômicos

* Qualquer gerador de números pseudo-randômicos começa a partir de algum valor, chamado de **semente**.

* A partir da semente o valor seguinte é gerado. Esse valor passa por algumas transformações para ser a semente do valor pseudo-aleatório seguinte.



In [ ]:
print( random.randint(100, size=10) )

[68 84 29 15 11 86 95 19 57 27]


In [ ]:
# Obrigando o Python a utilizar a mesma semente:

random.seed(0)
print( random.randint(100, size=10) )

NameError: ignored

In [ ]:
print( random.randint(100, size=10) )

[81 37 25 77 72  9 20 80 69 79]


In [ ]:
random.seed(0)
print( random.randint(100, size=10) )

print( random.randint(100, size=10) )

print( random.randint(100, size=10) )

[44 47 64 67 67  9 83 21 36 87]
[70 88 88 12 58 65 39 87 46 88]
[81 37 25 77 72  9 20 80 69 79]


In [ ]:
random.seed(0)
print( random.randint(100, size=10) )

print( random.randint(100, size=10) )

print( random.randint(100, size=10) )

[44 47 64 67 67  9 83 21 36 87]
[70 88 88 12 58 65 39 87 46 88]
[81 37 25 77 72  9 20 80 69 79]


## Funções Universais (ufuncs)

* **zip(lista1, lista2)**: retorna os elementos de mesmo índice das listas.

* **np.add(lista1, lista2)**: retorna um arranjo com a soma de elementos de mesmo índice das listas.

* **np.frompyfunc(function, inputs, outputs)**: faz com que operações de uma função sejam realizadas elemento a elemento.

In [ ]:
# Exemplo 1: Somar elementos de duas listas (dois a dois)
x = [1, 2, 3, 4]
y = [4, 5, 6, 7]

z = []

for i, j in zip(x, y):
  z.append(i + j)

print(z)

[5, 7, 9, 11]


In [ ]:
# Exemplo 2: Somar elementos de dois arranjos (numpy)
import numpy as np

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = np.add(x, y)

print(z)

[ 5  7  9 11]


In [ ]:
# Exemplo 3: Definindo uma função similar...
def myadd(lista1, lista2):
  import numpy as np
  z = []
  for i, j in zip(lista1, lista2):
    z.append(i + j)
  return np.array( z )

x = [1, 2, 3, 4]
y = [4, 5, 6, 7]
z = myadd(x, y)

print(z)

[ 5  7  9 11]


In [ ]:
# Exemplo 4: Definindo uma FUNÇÃO UNIVERSAL:
import numpy as np

def myadd(x, y):
  return x + y

print(x, y)
print(x + y)  # + funciona como operador de concatenação para listas

# np.frompyfunc(function, inputs, outputs)
# function - o nome da função
# inputs   - o número de argumentos de entrada (arrays/listas)
# outputs  - o número de arranjos na saída
# A função faz com que a operação da função myadd seja aplicada elemento por elemento
myadd2 = np.frompyfunc(myadd, 2, 1)
print(type(myadd2))

print()
print( myadd(x, y) )
print( myadd2(x, y) )

print()
print( myadd )
print( myadd2 ) # A função frompyfunc faz a vetorização, isto é, obriga a pegar
                # elemento por elemento

[1, 2, 3, 4] [4, 5, 6, 7]
[1, 2, 3, 4, 4, 5, 6, 7]
<class 'numpy.ufunc'>

[1, 2, 3, 4, 4, 5, 6, 7]
[5 7 9 11]

<function myadd at 0x7fa221fe8170>
<ufunc '? (vectorized)'>


### Checando se uma função é universal

* É universal a função que possui a classe **numpy.ufunc**.

In [ ]:
print( type(np.add) )  # Operações envolvendo elementos (vetorização)

<class 'numpy.ufunc'>


In [ ]:
print( type(np.concatenate) )  # Não realiza função envolvendo elementos

<class 'function'>


## Tipos de dados do NumPy

* **Inteiros:** 'int8', 'int16', 'int32', 'int64', 'int'
* **Inteiros sem sinal (unsigned int):** 'uint8', 'uint16', 'uint32', 'uint64', 'uint'
* **Reais:** 'float32', 'float64', 'float'
* **Complexos:** 'complex64', 'complex128', 'complex'
* **Booleanos:** 'bool'
* **Strings:** '<U9'

### Checando o tipo de dado no NumPy

* Para verificar o tipo de um elemento ou dos elementos de uma lista podemos usar **elemento/arranjo.dtype**.

* O **type(elemento)** também retorna a classe, mas se for um arranjo, não retorna a dos elementos.

In [ ]:
print( type(10) )

<class 'int'>


In [ ]:
import numpy as np
from numpy import random

arr = np.array( random.randint(20,size=5) )

print( arr, arr.dtype, arr[0].dtype, type(arr), type(arr[0]) )

[17 15  4  9 10] int64 int64 <class 'numpy.ndarray'> <class 'numpy.int64'>


In [ ]:
arr = np.array( random.rand(5) )
print(arr, arr.dtype)
# O número ao lado indica o espaço da memória que o elemento está ocupando

[0.3595079  0.43703195 0.6976312  0.06022547 0.66676672] float64


In [ ]:
import numpy as np

arr = np.array( ['Aldebaran', 'Betegeuse', 'Canopus'] )
print(arr.dtype)  # U9 -> unicode

<U9


In [ ]:
import numpy as np

arr = np.array( [True, True, False] )
print(arr.dtype)

bool


### Obtendo informações sobre os diferentes tipos de dados do NumPy

* Para verificar os limites de cada tipo de dado pode usar:
  * **np.iinfo(tipo)** para inteiros (e inteiros sem sinal);
  * **np.finfo(tipo)** para reais e complexos;
  * **np.info(tipo)** para booleanos.

In [ ]:
# Inteiros:
tipos = ['int8', 'int16', 'int32', 'int64', 'int']

for tipo in tipos:
  print( np.iinfo(tipo) )

# O int nativo do Python é interpretado como int64 pelo numpy

Machine parameters for int8
---------------------------------------------------------------
min = -128
max = 127
---------------------------------------------------------------

Machine parameters for int16
---------------------------------------------------------------
min = -32768
max = 32767
---------------------------------------------------------------

Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------

Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------



In [ ]:
# Inteiros sem sinal (unsigned integers):
tipos = ['uint8', 'uint16', 'uint32', 'uint64', 'uint']

for tipo in tipos:
  print( np.iinfo(tipo) )

Machine parameters for uint8
---------------------------------------------------------------
min = 0
max = 255
---------------------------------------------------------------

Machine parameters for uint16
---------------------------------------------------------------
min = 0
max = 65535
---------------------------------------------------------------

Machine parameters for uint32
---------------------------------------------------------------
min = 0
max = 4294967295
---------------------------------------------------------------

Machine parameters for uint64
---------------------------------------------------------------
min = 0
max = 18446744073709551615
---------------------------------------------------------------

Machine parameters for uint64
---------------------------------------------------------------
min = 0
max = 18446744073709551615
---------------------------------------------------------------



In [ ]:
# Floats:
tipos = ['float32', 'float64', 'float']

for tipo in tipos:
  print( np.finfo(tipo) )

Machine parameters for float32
---------------------------------------------------------------
precision =   6   resolution = 1.0000000e-06
machep =    -23   eps =        1.1920929e-07
negep =     -24   epsneg =     5.9604645e-08
minexp =   -126   tiny =       1.1754944e-38
maxexp =    128   max =        3.4028235e+38
nexp =        8   min =        -max
---------------------------------------------------------------

Machine parameters for float64
---------------------------------------------------------------
precision =  15   resolution = 1.0000000000000001e-15
machep =    -52   eps =        2.2204460492503131e-16
negep =     -53   epsneg =     1.1102230246251565e-16
minexp =  -1022   tiny =       2.2250738585072014e-308
maxexp =   1024   max =        1.7976931348623157e+308
nexp =       11   min =        -max
---------------------------------------------------------------

Machine parameters for float64
---------------------------------------------------------------
precision =  15 

In [ ]:
# Complexos:
tipos = ['complex64', 'complex128', 'complex']

for tipo in tipos:
  print( np.finfo(tipo) )

Machine parameters for float32
---------------------------------------------------------------
precision =   6   resolution = 1.0000000e-06
machep =    -23   eps =        1.1920929e-07
negep =     -24   epsneg =     5.9604645e-08
minexp =   -126   tiny =       1.1754944e-38
maxexp =    128   max =        3.4028235e+38
nexp =        8   min =        -max
---------------------------------------------------------------

Machine parameters for float64
---------------------------------------------------------------
precision =  15   resolution = 1.0000000000000001e-15
machep =    -52   eps =        2.2204460492503131e-16
negep =     -53   epsneg =     1.1102230246251565e-16
minexp =  -1022   tiny =       2.2250738585072014e-308
maxexp =   1024   max =        1.7976931348623157e+308
nexp =       11   min =        -max
---------------------------------------------------------------

Machine parameters for float64
---------------------------------------------------------------
precision =  15 

In [ ]:
# Booleanos:
tipos = ['bool']

for tipo in tipos:
  print( np.info(tipo) )

None


In [ ]:
# Strings:
tipos = ['<U9']

for tipo in tipos:
  print( np.info(tipo) )

None


### Criando arrays com um tipo definido de dado

* Quando o tipo não é especificado, o tipo de maior tamanho é utilizado como *default*.

* O tempo de processamento pode ser reduzido muito se definido o tipo de dado utilizado com **dtype**. 

In [ ]:
import numpy as np
from numpy import random

arr = np.array( random.randint(100, size=5), dtype='uint8' )

print(arr, arr.dtype)

[78 15 20 99 58] uint8


In [ ]:
import numpy as np
from numpy import random

arr = np.array( random.rand(5), dtype='float32' )

print(arr, arr.dtype)

[0.9883738  0.10204481 0.20887676 0.16130951 0.6531083 ] float32


### Alterando o tipo de um arranjo já existente

* A melhor maneira é gerando uma cópia utilizando **arranjo.astype(tipo)**.

* Mas também existem funções de conversão, por exemplo, **np.int64()**.

In [ ]:
# int64 --> int32
import numpy as np
from numpy import random

arr = np.array( random.randint(100, size=5) )

print(arr, arr.dtype)

newarr = arr.astype('int32')

print(newarr, newarr.dtype)

print(newarr.base)

[36 34 48 93  3] int64
[36 34 48 93  3] int32
None


In [ ]:
# float64 --> float32
import numpy as np
from numpy import random

arr = np.array( random.rand(5) )

print(arr, arr.dtype)

newarr = arr.astype('float32')

print(newarr, newarr.dtype)

[0.28280696 0.12019656 0.2961402  0.11872772 0.31798318] float64
[0.28280696 0.12019656 0.2961402  0.11872772 0.31798318] float32


In [ ]:
# int64 --> bool
import numpy as np
from numpy import random

arr = np.array( random.randint(5, size=5) )

print(arr, arr.dtype)

newarr = arr.astype('bool')

print(newarr, newarr.dtype)

# Todos os valores que não forem 0 serão True

[4 2 3 0 3] int64
[ True  True  True False  True] bool


In [ ]:
# int64 --> <U9 (Unicode, string)
import numpy as np
from numpy import random

arr = np.array( random.randint(5, size=5) )

print(arr, arr.dtype)

newarr = arr.astype('<U9')

print(newarr, newarr.dtype)

[2 3 0 0 0] int64
['2' '3' '0' '0' '0'] <U9


In [ ]:
# Erro por overflow (quando tenta armazenar um tipo fora de seus limites)
import numpy as np

x = np.int64( 100**8 )  # Converte para int64
print(x, x.dtype)
print()

y = np.int32( 100**8 )  # Converte para int32
print(y, y.dtype)       # Erro por overflow (armazenou alguma coisa, mas não o esperado)

10000000000000000 int64

1874919424 int32


In [ ]:
# Diferentemente das funções int(), float(), etc que retornam o tipo vazio
# As funções do numpy int64(), etc são apenas funções de converção e vazias geram exceção
print( int(), float() )
print( int64(), float32() )

0 0.0


NameError: ignored